[package]
name = "squads-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
squads-multisig = "2.1.0"
solana-sdk = "1.18"
solana-client = "1.18"
tokio = { version = "1", features = ["full"] }
spl-token = "4.0.0"
spl-associated-token-account = "2.3.0"
